### ISSUE TITLE
UNABLE TO FIND DIRECTORY TO PATHS USING CONFIG

### ISSUE THREAD

**Issue by xAlphaOmega** [initOS/odoo-analyse#2]
**When running the command as indicated it produces the following error**
Command: 
odoo_analyse --config odoo-server.conf
odoo_analyse -c /full/path/ooo-server.con
f
**Traceback:** 
Traceback (most recent call last):
  File "/odoo-prod/cypress-prod/env/bin/odoo_analyse", line 8, in <module>
    sys.exit(main())
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/main.py", line 202, in main
    odoo = Odoo.from_config(args.config)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/odoo.py", line 34, in from_config
    odoo.load(config_path)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/odoo.py", line 129, in load
    self.load_path(paths, depth=1)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/odoo.py", line 201, in load_path
    result = Module.find_modules(paths, depth=depth)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/module.py", line 401, in find_modules
    for p in os.listdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '\n/odoo-prod/cypress-prod/src/odoo/addons'

**Comment by fkantelberg** [comment]
@xAlphaOmega It seems like you have line breaks in your odoo configuration file. We added some code to strip them with c00ca1e8fa42e073dceab0d970b5e25136d6f434. I hope that fixed it.
