### ISSUE TITLE
PATHS CONFIGURATION FAILED

### ISSUE THREAD

**Issue by xAlphaOmega** [initOS/odoo-analyse#3]
Attempted to run odoo_analyse with path and it doesn't work
odoo_analyse --path local

Traceback (most recent call last):
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/module.py", line 389, in find_modules
    module = cls.from_path(path)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/module.py", line 366, in from_path
    module.analyse_hash(files_list)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/module.py", line 147, in analyse_hash
    self.hashsum = hexhash_files(files_list)
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/utils.py", line 57, in hexhash_files
    hashsum = hexhash(open(f, "rb").read())
FileNotFoundError: [Errno 2] No such file or directory: 'local/oca_off/stock-logistics-reporting/setup/stock_picking_report_valued/odoo/addons/stock_picking_report_valued/local/oca_off/stock-logistics-reporting/setup/stock_picking_report_valued/odoo/addons/stock_picking_report_valued/__init__.py'
Traceback (most recent call last):
  File "/odoo-prod/cypress-prod/env/bin/odoo_analyse", line 8, in <module>
    sys.exit(main())
  File "/odoo-prod/cypress-prod/env/lib/python3.7/site-packages/odoo_analyse/main.py", line 236, in main
    if args.dependency_graph or args.import_graph or args.reference_graph:
AttributeError: 'Namespace' object has no attribute 'dependency_graph'

**Comment by fkantelberg** [comment]
@xAlphaOmega Thank you for your feedback. Seems like we missed some thing during the refactoring. c00ca1e8fa42e073dceab0d970b5e25136d6f434
